version: '3.8'

services:
  db:
    image: mysql:8
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - ${DB_PORT}:3306
    volumes:
      - db-storage:/var/lib/mysql
  
  web:
    build: .
    container_name: web
    ports:
      - ${PORT}:${PORT}
    environment:
      PORT: ${PORT}
      DB_HOST: ${DB_HOST_DOCKER}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DATABASE_URL: ${DATABASE_URL_DOCKER}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - db
volumes:
  db-storage:
    driver: local
